# Generated by Django 5.1.1 on 2024-09-23 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wifi', '0002_userpackage'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='minutes_limit',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
